# Generated by Django 3.2.6 on 2021-08-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2coffee', '0006_auto_20210826_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('BREWING', 'Brewing'), ('IDLE', 'Idle')], default='IDLE', max_length=7),
        ),
    ]
