# Generated by Django 3.2.7 on 2021-09-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("p2coffee", "0007_auto_20210830_0905"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="avatar_path",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
