# Generated by Django 3.2.7 on 2021-09-03 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("p2coffee", "0008_machine_avatar_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="brew",
            name="status",
            field=models.CharField(
                choices=[("brewing", "Brewing"), ("finished", "Finished")], default="brewing", max_length=8
            ),
        ),
        migrations.AlterField(
            model_name="brew",
            name="finished_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brews_finished",
                to="p2coffee.coffeepotevent",
            ),
        ),
    ]
