# Generated by Django 3.2.7 on 2021-09-05 15:59

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("p2coffee", "0009_auto_20210903_1558"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlackProfile",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("user_id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("display_name", models.CharField(blank=True, default="", max_length=255)),
                ("real_name", models.CharField(blank=True, default="", max_length=255)),
                ("image_original", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
