# Generated by Django 3.2.7 on 2021-09-05 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("p2coffee", "0010_slackprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brew",
            name="brewer_slack_username",
        ),
        migrations.RemoveField(
            model_name="brewreaction",
            name="slack_username",
        ),
        migrations.AddField(
            model_name="brew",
            name="brewer",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="p2coffee.slackprofile"
            ),
        ),
        migrations.AddField(
            model_name="brew",
            name="slack_channel",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="brew",
            name="slack_ts",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="brewreaction",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="p2coffee.slackprofile"
            ),
        ),
        migrations.AlterField(
            model_name="brew",
            name="finished_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brews_finished",
                to="p2coffee.sensorevent",
            ),
        ),
        migrations.AlterField(
            model_name="brew",
            name="started_event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="brews_started", to="p2coffee.sensorevent"
            ),
        ),
    ]
