version: '3'
services:
    redis:
        image: redis
        ports:
            - "6379:6379"
    web:
        build:
            context: .
        ports:
            - "8000:8000"
        links: [redis, mq]
    worker:
        build:
            context: .
        command: [python, manage.py, run_huey, -w, "2"]
        links: [redis, mq]
    mq:
        image: eclipse-mosquitto
        ports:
          - 1883:1883
          - 9001:9001
        # volumes:
        #   - mosquitto.conf:/mosquitto/config/mosquitto.conf
