version: '3'
services:
    redis:
        image: redis
        ports:
            - "6379:6379"
    web:
        build:
            context: .
        ports:
            - "8000:8000"
    worker:
        build:
            context: .
        command: [python, manage.py, run_huey, -w, "2"]
